name: Deploy via FTP

on: 
  push:
    branches:
      - main  # Altere para a branch que você deseja monitorar para deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "dist"  # Altere para o diretório local que contém os arquivos a serem enviados
        remoteDir: "/caminho/para/seu/projeto"  # Altere para o diretório no servidor remoto onde os arquivos serão enviados
