name: Deploy to Locaweb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Locaweb
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp://ftp.seusite.com.br
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /caminho/para/seu/projeto
